baseURL = "https://pedroql.github.io/mvflow/"
languageCode = "en-GB"
title = "MVFLow: a simple MVI library using Kotlin coroutines and flows"
theme = "mypurecss"

[params]
    custom_css = ["css/github.css"]

[markup]
  [markup.highlight]
    codeFences = true
    style = "tango"
